### ISSUE TITLE
Plotting queue empty, exiting plotting_thread

### ISSUE THREAD

**Issue by zoldaten** [muxamilian/wyhiwys#1]
```
python learn.py --mode live --video_source 0

Got these arguments: Namespace(mode='live', video_source='0', weights='logs//20220311-233556//weights.106--0.00333//variables//variables', data_dir=None)
is_file False
audio latency: 0.10
Exception in thread Thread-1 (produce_new_frame):
Traceback (most recent call last):
  File "C:\Users\user\.pyenv\pyenv-win\versions\3.10.9\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\user\.pyenv\pyenv-win\versions\3.10.9\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\user\Desktop\2\wysiwyh\learn.py", line 209, in produce_new_frame
    process_new_frame_queue.get(block=True, timeout=1)
  File "C:\Users\user\.pyenv\pyenv-win\versions\3.10.9\lib\queue.py", line 179, in get
    raise Empty
_queue.Empty
Plotting queue empty, exiting plotting_thread
```

numpy-1.23.1
tensorflow==2.10.0
tensorflow-addons==0.22.0
tensorflow-datasets==4.9.4
tensorflow-estimator==2.10.0
tensorflow-intel==2.11.0
tensorflow-io==0.31.0
tensorflow-io-gcs-filesystem==0.31.0
tensorflow-metadata==1.14.0
tensorflow-probability==0.12.0
pyaudio==0.2.14
matplotlib==3.9.2

**Comment by zoldaten** [comment]
ok. fixed that!
in learn.py just removed timeout:
```
#process_new_frame_queue.get(block=True, timeout=1)
process_new_frame_queue.get(block=True)
```

**Comment by muxamilian** [comment]
I'm glad that you could make it work for you, so we can close this?
